version: "3.3"
services:
    app:
        image: grafana/grafana-oss
        container_name: grafana
        restart: on-failure
        ports:
          - "80:3000"
        depends_on:
          - db
        volumes:
          - grafana:/var/lib/grafana
          - ./grafana.ini:/etc/grafana/grafana.ini
        networks:
          - grafana_net

    db:
        image: influxdb
        container_name: influxdb
        restart: on-failure
        ports:
          - "8086:8086"
        volumes:
          - influx_vol:/var/lib/influxdb2
        environment:
          - INFLUXDB_DB=grafana
          - INFLUXDB_ADMIN_USER=admin
          - INFLUXDB_ADMIN_PASSWORD=Filab2022!
          - INFLUXDB_USER=user
          - INFLUXDB_USER_PASSWORD=
        networks:
          - grafana_net

volumes:
    grafana:
    influx_vol:
networks:
    grafana_net:
