 version: "3.3"

services:
  app:
    image: grafana/grafana-oss
    container_name: grafana
    restart: on-failure
    ports:
      - "80:3000"
    depends_on:
      - db
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini
      - grafana:/var/lib/grafana
    networks:
      - grafana_net

  db:
    image: influxdb
    container_name: influxdb
    restart: on-failure
    ports:
      - "8086:8086"
    volumes:
      - influx_vol:/var/lib/influxdb2
    environment:
      - INFLUXDB_DB=grafana
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=Filab2022!
      - INFLUXDB_USER=schulung
      - INFLUXDB_USER_PASSWORD=Filab2022!
      - DOCKER_INFLUXDB_INIT_MODE=setup 
      - DOCKER_INFLUXDB_INIT_USERNAME=schulung
      - DOCKER_INFLUXDB_INIT_PASSWORD=Filab2022!
      - DOCKER_INFLUXDB_INIT_ORG=lucka
      - DOCKER_INFLUXDB_INIT_BUCKET=grafana_bucket
      - INFLUX_TOKEN=Y1V3dpobqkW52ZTRoQ9FVzF35RFaB3wvucpkKhibWhtsP4g8WXvNvwJiL4-PI8nkrKUf4tQeY5bP5_gptZDQgA==
    networks:
      - grafana_net

volumes:
  grafana:
  influx_vol:

networks:
  grafana_net:
